// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR5Pr3b1Cqt_qvbyIo7e92M0n7z-0KkxU',
    appId: '1:989368306264:android:6c1b5eace5a73149d0982d',
    messagingSenderId: '989368306264',
    projectId: 'watch-a-movie-5a7e8',
    storageBucket: 'watch-a-movie-5a7e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmJ6L-3t1HdfbmE-JrRGbHmhHlf1EPA1A',
    appId: '1:989368306264:ios:a220c6424d1757f4d0982d',
    messagingSenderId: '989368306264',
    projectId: 'watch-a-movie-5a7e8',
    storageBucket: 'watch-a-movie-5a7e8.appspot.com',
    iosClientId: '989368306264-jtv0ti3oo24u5ek9lb4cavdee15t6tl0.apps.googleusercontent.com',
    iosBundleId: 'com.kubaolszewski.watchAMovie',
  );
}
